kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apollo-configservice
  namespace: infra
  labels:
    name: apollo-configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apollo-configservice
  template:
    metadata:
      labels:
        app: apollo-configservice
        name: apollo-configservice
    spec:
      nodeName: node3
      volumes:
      - name: configmap-volume
        configMap:
          name: apollo-configservice-cm
      containers:
      - name: apollo-configservice
        image: apollo-configservice:v1.4.0
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: configmap-volume
          mountPath: /apollo-configservice/config
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      #imagePullSecrets:
      #- name: harbor
      #restartPolicy: Always
      #terminationGracePeriodSeconds: 30
      #securityContext:
      #  runAsUser: 0
      #schedulerName: default-scheduler
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxUnavailable: 1
  #    maxSurge: 1
  #revisionHistoryLimit: 7
  #progressDeadlineSeconds: 600
